name: API-Fuzzing-Pipeline

on:
  pull_request:
    branches: [ "main", "master" ]
  push:
    branches: [ "main" ]
  schedule:
    - cron: "0 3 * * *" # nightly fuzzing run at 3AM UTC

permissions:
  contents: read
  security-events: write
  actions: read
  checks: write

jobs:

  lint-and-prepare:
    name: Lint Schemas & Prepare Environment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt || true
          pip install jsonschema || true

      - name: Validate OpenAPI Spec
        run: |
          if [ -f "openapi.yaml" ]; then
            pip install openapi-spec-validator
            openapi-spec-validator openapi.yaml
          fi

      - name: Cache Wordlists
        uses: actions/cache@v4
        with:
          path: fuzzing/wordlists
          key: fuzzwordlists-${{ runner.os }}

  fuzz-api:
    name: API Fuzzing Stage
    needs: lint-and-prepare
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Fuzzing Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y ffuf jq unzip
          pip install requests

      - name: Download RESTler
        run: |
          wget https://github.com/microsoft/restler-fuzzer/releases/latest/download/restler.zip -O restler.zip
          unzip restler.zip -d tools/restler/

      - name: Run ffuf (Parameter Fuzzing)
        run: |
          ffuf -u "https://api.example.com/v1/users?search=FUZZ" \
               -w fuzzing/wordlists/common.txt \
               -t 50 \
               -timeout 5 \
               -mc all \
               -o ffuf-results.json -of json

      - name: Run RESTler (Model-Based Fuzzing)
        run: |
          if [ -f openapi.json ]; then
            tools/restler/restler compile --api_spec openapi.json
            tools/restler/restler fuzz-lean --time_budget 15
          fi

      - name: Run Custom Python Fuzzer Suite
        run: |
          python fuzzing/run_fuzzer.py --config fuzzing/config/api_fuzz.yaml

      - name: Upload Fuzzing Reports
        uses: actions/upload-artifact@v4
        with:
          name: fuzzing-reports
          path: |
            ffuf-results.json
            RestlerResults/*
            fuzzing/logs/*

  stress-and-rate-limit:
    name: Load + Fault Injection Stage
    needs: fuzz-api
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install k6
        run: |
          sudo apt-get update
          sudo apt-get install -y ca-certificates curl gnupg
          curl -s https://dl.k6.io/key.gpg | sudo apt-key add -
          echo "deb https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list
          sudo apt-get update
          sudo apt-get install -y k6

      - name: Run k6 Fault Injection
        run: |
          k6 run fuzzing/scripts/k6-fuzz.js

      - name: Upload Stress Test Logs
        uses: actions/upload-artifact@v4
        with:
          name: stress-test-logs
          path: k6-results/*

  security-summary:
    name: Security Summary
    runs-on: ubuntu-latest
    needs: [ fuzz-api, stress-and-rate-limit ]

    steps:
      - name: Generate Summary
        run: |
          echo "## API Fuzzing Summary Report" >> $GITHUB_STEP_SUMMARY
          echo "- RESTler results: ✔️" >> $GITHUB_STEP_SUMMARY
          echo "- ffuf mutation fuzzing: ✔️" >> $GITHUB_STEP_SUMMARY
          echo "- Custom fuzz suite executed: ✔️" >> $GITHUB_STEP_SUMMARY
          echo "- k6 rate-limit & slowloris tests: ✔️" >> $GITHUB_STEP_SUMMARY

